language: csharp
sudo: required
mono: none
dotnet: 2.2.401
script:
 - cd src
 - dotnet build -c Release
 - dotnet test -c Release --no-build unittests/DoOrSave.UnitTests/DoOrSave.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)